FROM mcr.microsoft.com/dotnet/sdk:8.0-cbl-mariner2.0-amd64 AS builder

WORKDIR /source

COPY . .

RUN dotnet publish -r linux-x64 --self-contained true

FROM --platform=linux/amd64 ubuntu/dotnet-deps:8.0-24.04_stable

WORKDIR /app

COPY --from=builder /source/bin/Release/net8.0/linux-x64/publish .

ENV TZ=UTC

ENTRYPOINT ["./API"]
