//import { createSlice, createAsyncThunk } from "@reduxjs/toolkit"
import { createSlice } from "@reduxjs/toolkit"
import type { PayloadAction } from "@reduxjs/toolkit" // För att typa action.payload i reducer-funktioner
import Common from "../../types/common/Common"


// Initial state

const initialState: Common ={
    currencies: [
        { id: 1, label: "US Dollar", code: "USD", currencyPerUsd: null },
        { id: 2, label: "Euro", code: "EUR", currencyPerUsd: null },
        { id: 3, label: "Japanese Yen", code: "JPY", currencyPerUsd: null },
        { id: 4, label: "British Pound", code: "GBP", currencyPerUsd: null },
        { id: 5, label: "Australian Dollar", code: "AUD", currencyPerUsd: null },
        { id: 6, label: "Canadian Dollar", code: "CAD", currencyPerUsd: null },
        { id: 7, label: "Swiss Franc", code: "CHF", currencyPerUsd: null },
        { id: 8, label: "Chinese Yuan", code: "CNY", currencyPerUsd: null },
        { id: 9, label: "Swedish Krona", code: "SEK", currencyPerUsd: null },
        { id: 10, label: "New Zealand Dollar", code: "NZD", currencyPerUsd: null },
        { id: 11, label: "Mexican Peso", code: "MXN", currencyPerUsd: null },
        { id: 12, label: "Singapore Dollar", code: "SGD", currencyPerUsd: null },
        { id: 13, label: "Hong Kong Dollar", code: "HKD", currencyPerUsd: null },
        { id: 14, label: "Norwegian Krone", code: "NOK", currencyPerUsd: null },
        { id: 15, label: "South Korean Won", code: "KRW", currencyPerUsd: null },
        { id: 16, label: "Turkish Lira", code: "TRY", currencyPerUsd: null },
        { id: 17, label: "Russian Ruble", code: "RUB", currencyPerUsd: null },
        { id: 18, label: "Indian Rupee", code: "INR", currencyPerUsd: null },
        { id: 19, label: "Brazilian Real", code: "BRL", currencyPerUsd: null },
        { id: 20, label: "South African Rand", code: "ZAR", currencyPerUsd: null },
        { id: 21, label: "Philippine Peso", code: "PHP", currencyPerUsd: null },
        { id: 22, label: "Indonesian Rupiah", code: "IDR", currencyPerUsd: null },
        { id: 23, label: "Saudi Riyal", code: "SAR", currencyPerUsd: null },
        { id: 24, label: "Malaysian Ringgit", code: "MYR", currencyPerUsd: null },
        { id: 25, label: "United Arab Emirates Dirham", code: "AED", currencyPerUsd: null },
        { id: 26, label: "Polish Zloty", code: "PLN", currencyPerUsd: null },
        { id: 27, label: "Chilean Peso", code: "CLP", currencyPerUsd: null },
        { id: 28, label: "Thai Baht", code: "THB", currencyPerUsd: null },
        { id: 29, label: "Israeli Shekel", code: "ILS", currencyPerUsd: null },
        { id: 30, label: "Egyptian Pound", code: "EGP", currencyPerUsd: null },
        { id: 31, label: "Colombian Peso", code: "COP", currencyPerUsd: null },
        { id: 32, label: "Danish Krone", code: "DKK", currencyPerUsd: null },
        { id: 33, label: "Jordanian Dinar", code: "JOD", currencyPerUsd: null },
        { id: 34, label: "Czech Koruna", code: "CZK", currencyPerUsd: null },
        { id: 35, label: "Peruvian Sol", code: "PEN", currencyPerUsd: null },
        { id: 36, label: "Ukrainian Hryvnia", code: "UAH", currencyPerUsd: null },
        { id: 37, label: "Hungarian Forint", code: "HUF", currencyPerUsd: null },
        { id: 38, label: "Vietnamese Dong", code: "VND", currencyPerUsd: null },
        { id: 39, label: "Kuwaiti Dinar", code: "KWD", currencyPerUsd: null },
        { id: 40, label: "New Taiwan Dollar", code: "TWD", currencyPerUsd: null },
        { id: 41, label: "Qatari Riyal", code: "QAR", currencyPerUsd: null },
        { id: 42, label: "Romanian Leu", code: "RON", currencyPerUsd: null },
        { id: 43, label: "Argentine Peso", code: "ARS", currencyPerUsd: null },
        { id: 44, label: "Bahraini Dinar", code: "BHD", currencyPerUsd: null },
        { id: 45, label: "Omani Rial", code: "OMR", currencyPerUsd: null },
        { id: 46, label: "Costa Rican Colon", code: "CRC", currencyPerUsd: null },
        { id: 47, label: "Panamanian Balboa", code: "PAB", currencyPerUsd: null },
        { id: 48, label: "Guatemalan Quetzal", code: "GTQ", currencyPerUsd: null },
        { id: 49, label: "Uruguayan Peso", code: "UYU", currencyPerUsd: null },
        { id: 50, label: "Bolivian Boliviano", code: "BOB", currencyPerUsd: null },
        { id: 51, label: "Honduran Lempira", code: "HNL", currencyPerUsd: null },
        { id: 52, label: "Nicaraguan Cordoba", code: "NIO", currencyPerUsd: null },
        { id: 53, label: "Paraguayan Guarani", code: "PYG", currencyPerUsd: null },
        { id: 54, label: "El Salvadoran Colon", code: "SVC", currencyPerUsd: null },
        { id: 55, label: "Croatian Kuna", code: "HRK", currencyPerUsd: null },
        { id: 56, label: "Lebanese Pound", code: "LBP", currencyPerUsd: null },
        { id: 57, label: "Serbian Dinar", code: "RSD", currencyPerUsd: null },
        { id: 58, label: "Algerian Dinar", code: "DZD", currencyPerUsd: null },
        { id: 59, label: "Moroccan Dirham", code: "MAD", currencyPerUsd: null },
        { id: 60, label: "Ethiopian Birr", code: "ETB", currencyPerUsd: null },
        { id: 61, label: "Tunisian Dinar", code: "TND", currencyPerUsd: null },
        { id: 62, label: "Libyan Dinar", code: "LYD", currencyPerUsd: null },
        { id: 63, label: "Ghanaian Cedi", code: "GHS", currencyPerUsd: null },
        { id: 64, label: "Nigerian Naira", code: "NGN", currencyPerUsd: null },
        { id: 65, label: "Kenyan Shilling", code: "KES", currencyPerUsd: null },
        { id: 66, label: "Ugandan Shilling", code: "UGX", currencyPerUsd: null },
        { id: 67, label: "Zambian Kwacha", code: "ZMW", currencyPerUsd: null },
        { id: 68, label: "Namibian Dollar", code: "NAD", currencyPerUsd: null },
        { id: 69, label: "Mauritian Rupee", code: "MUR", currencyPerUsd: null },
        { id: 70, label: "Tanzanian Shilling", code: "TZS", currencyPerUsd: null },
        { id: 71, label: "Uzbekistani Som", code: "UZS", currencyPerUsd: null },
        { id: 72, label: "Iraqi Dinar", code: "IQD", currencyPerUsd: null },
        { id: 73, label: "Iranian Rial", code: "IRR", currencyPerUsd: null },
        { id: 74, label: "Afghan Afghani", code: "AFN", currencyPerUsd: null },
        { id: 75, label: "Pakistani Rupee", code: "PKR", currencyPerUsd: null },
        { id: 76, label: "Bangladeshi Taka", code: "BDT", currencyPerUsd: null },
        { id: 77, label: "Sri Lankan Rupee", code: "LKR", currencyPerUsd: null },
        { id: 78, label: "Nepalese Rupee", code: "NPR", currencyPerUsd: null },
        { id: 79, label: "Maldivian Rufiyaa", code: "MVR", currencyPerUsd: null },
        { id: 80, label: "Cambodian Riel", code: "KHR", currencyPerUsd: null },
        { id: 81, label: "Bhutanese Ngultrum", code: "BTN", currencyPerUsd: null },
        { id: 82, label: "Brunei Dollar", code: "BND", currencyPerUsd: null },
        { id: 83, label: "Fijian Dollar", code: "FJD", currencyPerUsd: null },
        { id: 84, label: "Tongan Pa'anga", code: "TOP", currencyPerUsd: null },
        { id: 85, label: "Solomon Islands Dollar", code: "SBD", currencyPerUsd: null },
        { id: 86, label: "Papua New Guinean Kina", code: "PGK", currencyPerUsd: null },
        { id: 87, label: "Samoa Tala", code: "WST", currencyPerUsd: null },
        { id: 88, label: "Vanuatu Vatu", code: "VUV", currencyPerUsd: null },
        { id: 89, label: "Central African CFA Franc", code: "XAF", currencyPerUsd: null },
        { id: 90, label: "East Caribbean Dollar", code: "XCD", currencyPerUsd: null },
        { id: 91, label: "West African CFA Franc", code: "XOF", currencyPerUsd: null },
        { id: 92, label: "Comorian Franc", code: "KMF", currencyPerUsd: null },
        { id: 93, label: "Djiboutian Franc", code: "DJF", currencyPerUsd: null },
        { id: 94, label: "Eritrean Nakfa", code: "ERN", currencyPerUsd: null },
        { id: 95, label: "CFP Franc", code: "XPF", currencyPerUsd: null },
        { id: 96, label: "Gibraltar Pound", code: "GIP", currencyPerUsd: null },
        { id: 97, label: "Saint Helena Pound", code: "SHP", currencyPerUsd: null },
        { id: 98, label: "Falkland Islands Pound", code: "FKP", currencyPerUsd: null },
        { id: 99, label: "Jersey Pound", code: "JEP", currencyPerUsd: null },
        { id: 100, label: "Manx Pound", code: "IMP", currencyPerUsd: null },
        { id: 101, label: "Guernsey Pound", code: "GGP", currencyPerUsd: null },
        { id: 102, label: "Bermudian Dollar", code: "BMD", currencyPerUsd: null },
        { id: 103, label: "Saint Kitts and Nevis Dollar", code: "XCD", currencyPerUsd: null },
        { id: 104, label: "Cayman Islands Dollar", code: "KYD", currencyPerUsd: null },
        { id: 105, label: "Cuban Convertible Peso", code: "CUC", currencyPerUsd: null },
        { id: 106, label: "Cuban Peso", code: "CUP", currencyPerUsd: null },
        { id: 107, label: "Dutch Guilder", code: "ANG", currencyPerUsd: null },
        { id: 108, label: "Guyanaese Dollar", code: "GYD", currencyPerUsd: null },
        { id: 109, label: "Haitian Gourde", code: "HTG", currencyPerUsd: null },
        { id: 110, label: "Jamaican Dollar", code: "JMD", currencyPerUsd: null },
        { id: 111, label: "Surinamese Dollar", code: "SRD", currencyPerUsd: null },
        { id: 112, label: "Trinidad and Tobago Dollar", code: "TTD", currencyPerUsd: null },
        { id: 113, label: "Bahamian Dollar", code: "BSD", currencyPerUsd: null },
        { id: 114, label: "Barbadian Dollar", code: "BBD", currencyPerUsd: null },
        { id: 115, label: "Belize Dollar", code: "BZD", currencyPerUsd: null },
        { id: 116, label: "Panamanian Balboa", code: "PAB", currencyPerUsd: null },
        { id: 117, label: "Aruban Florin", code: "AWG", currencyPerUsd: null },
    ],
    genders: [
        {id: 1, label: "Female"},
        {id: 2, label: "Male"},
        {id: 3, label: "Non-binary"},
        {id: 4, label: "Transgender"},
        {id: 5, label: "Other gender"},        
    ],
    languages: [
        { "id": 1, label: "English (United Kingdom)", code: "en-gb" },
        { "id": 2, label: "English (United States)", code: "en-us" },
        { "id": 3, label: "Spanish", code: "es" },
        { "id": 4, label: "French", code: "fr" },
        { "id": 5, label: "German", code: "de" },
        { "id": 6, label: "Italian", code: "it" },
        { "id": 7, label: "Portuguese", code: "pt" },
        { "id": 8, label: "Russian", code: "ru" },
        { "id": 9, label: "Chinese (Simplified)", code: "zh-cn" },
        { "id": 10, label: "Chinese (Traditional)", code: "zh-tw" },
        { "id": 11, label: "Japanese", code: "ja" },
        { "id": 12, label: "Korean", code: "ko" },
        { "id": 13, label: "Arabic", code: "ar" },
        { "id": 14, label: "Hindi", code: "hi" },
        { "id": 15, label: "Bengali", code: "bn" },
        { "id": 16, label: "Urdu", code: "ur" },
        { "id": 17, label: "Turkish", code: "tr" },
        { "id": 18, label: "Dutch", code: "nl" },
        { "id": 19, label: "Swedish", code: "sv" },
        { "id": 20, label: "Norwegian", code: "no" },
        { "id": 21, label: "Danish", code: "da" },
        { "id": 22, label: "Finnish", code: "fi" },
        { "id": 23, label: "Greek", code: "el" },
        { "id": 24, label: "Hebrew", code: "he" },
        { "id": 25, label: "Polish", code: "pl" },
        { "id": 26, label: "Thai", code: "th" },
        { "id": 27, label: "Vietnamese", code: "vi" },
        { "id": 28, label: "Indonesian", code: "id" },
        { "id": 29, label: "Malay", code: "ms" },
        { "id": 30, label: "Tagalog", code: "tl" },
        { "id": 31, label: "Swahili", code: "sw" },
        { "id": 32, label: "Czech", code: "cs" },
        { "id": 33, label: "Slovak", code: "sk" },
        { "id": 34, label: "Hungarian", code: "hu" },
        { "id": 35, label: "Romanian", code: "ro" },
        { "id": 36, label: "Bulgarian", code: "bg" },
        { "id": 37, label: "Ukrainian", code: "uk" },
        { "id": 38, label: "Croatian", code: "hr" },
        { "id": 39, label: "Serbian", code: "sr" },
        { "id": 40, label: "Slovenian", code: "sl" },
        { "id": 41, label: "Estonian", code: "et" },
        { "id": 42, label: "Latvian", code: "lv" },
        { "id": 43, label: "Lithuanian", code: "lt" },
        { "id": 44, label: "Georgian", code: "ka" },
        { "id": 45, label: "Armenian", code: "hy" },
        { "id": 46, label: "Azerbaijani", code: "az" },
        { "id": 47, label: "Kazakh", code: "kk" },
        { "id": 48, label: "Kyrgyz", code: "ky" },
        { "id": 49, label: "Tajik", code: "tg" },
        { "id": 50, label: "Uzbek", code: "uz" },
        { "id": 51, label: "Turkmen", code: "tk" },
        { "id": 52, label: "Mongolian", code: "mn" },
        { "id": 53, label: "Nepali", code: "ne" },
        { "id": 54, label: "Pashto", code: "ps" },
        { "id": 55, label: "Tamil", code: "ta" },
        { "id": 56, label: "Telugu", code: "te" },
        { "id": 57, label: "Marathi", code: "mr" },
        { "id": 58, label: "Gujarati", code: "gu" },
        { "id": 59, label: "Kannada", code: "kn" },
        { "id": 60, label: "Malayalam", code: "ml" },
        { "id": 61, label: "Sinhala", code: "si" },
        { "id": 62, label: "Burmese", code: "my" },
        { "id": 63, label: "Khmer", code: "km" },
        { "id": 64, label: "Lao", code: "lo" },
        { "id": 65, label: "Tibetan", code: "bo" },
        { "id": 66, label: "Dzongkha", code: "dz" },
        { "id": 67, label: "Kiribati", code: "gil" },
        { "id": 68, label: "Marshallese", code: "mh" },
        { "id": 69, label: "Nauruan", code: "na" },
        { "id": 70, label: "Palauan", code: "pau" },
        { "id": 71, label: "Samoan", code: "sm" },
        { "id": 72, label: "Tongan", code: "to" },
        { "id": 73, label: "Tuvaluan", code: "tvl" },
        { "id": 74, label: "Hawaiian", code: "haw" },
        { "id": 75, label: "Fijian", code: "fj" },
        { "id": 76, label: "Chamorro", code: "ch" },
        { "id": 77, label: "Carolino", code: "cal" },
        { "id": 78, label: "Kosraean", code: "kos" },
        { "id": 79, label: "Pohnpeian", code: "pon" },
        { "id": 80, label: "Trukese", code: "chk" },
        { "id": 81, label: "Woleaian", code: "wol" },
        { "id": 82, label: "Yapese", code: "yap" },
        { "id": 83, label: "Maori", code: "mi" },
        { "id": 84, label: "Tahitian", code: "ty" },
        { "id": 85, label: "Rapa Nui", code: "rap" },
        { "id": 86, label: "Cook Islands Maori", code: "rar" },
        { "id": 87, label: "Niuean", code: "niu" },
        { "id": 88, label: "Tokelauan", code: "tkl" },
        { "id": 89, label: "Rotuman", code: "rof" },
        { "id": 90, label: "Bislama", code: "bi" },
        { "id": 91, label: "Fijian Hindustani", code: "hif" },
        { "id": 92, label: "Hawaiian Creole", code: "hwc" },
        { "id": 93, label: "Norfuk / Pitkern", code: "pih" },
        { "id": 94, label: "Guaraní", code: "gn" },
        { "id": 95, label: "Aymara", code: "ay" },
        { "id": 96, label: "Quechua", code: "qu" },
        { "id": 97, label: "Mapudungun", code: "arn" },
        { "id": 98, label: "Tupi Guarani", code: "tpw" },
        { "id": 99, label: "Guarani Kaiowá", code: "gyr" },
        { "id": 100, label: "Arawak", code: "arw" },
        { "id": 101, label: "Nahuatl", code: "nah" },
        { "id": 102, label: "Tzotzil", code: "tzo" },
        { "id": 103, label: "Mixtec", code: "mix" },
        { "id": 104, label: "Zapotec", code: "zap" },
        { "id": 105, label: "Otomi", code: "otm" },
        { "id": 106, label: "Tarasco", code: "tzt" },
        { "id": 107, label: "Purépecha", code: "tsz" },
        { "id": 108, label: "Maya", code: "yua" },
        { "id": 109, label: "K'iche'", code: "quc" },
        { "id": 110, label: "Tz'utujil", code: "tzj" },
        { "id": 111, label: "Ixcatec", code: "ixc" },
        { "id": 112, label: "Chinantec", code: "chj" },
        { "id": 113, label: "Mixe", code: "mxq" },
        { "id": 114, label: "Zoque", code: "zoc" },
        { "id": 115, label: "Huasteco", code: "hus" },
        { "id": 116, label: "Pame", code: "paa" },
        { "id": 117, label: "Kikapú", code: "kic" },
        { "id": 118, label: "Seri", code: "sei" },
        { "id": 119, label: "Kumiai", code: "dih" },
        { "id": 120, label: "Tlapaneco", code: "tcf" },
        { "id": 121, label: "Cora", code: "crn" },
        { "id": 122, label: "Tepehua", code: "tpt" },
        { "id": 123, label: "Chinantec", code: "ctc" },
        { "id": 124, label: "Zoque", code: "zoh" },
        { "id": 125, label: "Huave", code: "huv" },
        { "id": 126, label: "Chontal", code: "chd" },
        { "id": 127, label: "Tojolabal", code: "toj" },
        { "id": 128, label: "Ixil", code: "ixl" },
        { "id": 129, label: "Jakaltek", code: "jac" },
        { "id": 130, label: "Mam", code: "mam" },
        { "id": 131, label: "Q'eqchi'", code: "kek" },
        { "id": 132, label: "Ch'orti'", code: "caa" },
        { "id": 133, label: "Sipakapense", code: "qum" },
        { "id": 134, label: "Poqomchi'", code: "poc" },
        { "id": 135, label: "Achi'", code: "acr" },
        { "id": 136, label: "Mopan", code: "mop" },
        { "id": 137, label: "Yucatec", code: "yua" },
        { "id": 138, label: "Tektitek", code: "ttc" },
        { "id": 139, label: "Sakapultek", code: "qqu" },
        { "id": 140, label: "Quiché", code: "quc" },
        { "id": 141, label: "Awakatek", code: "agu" },
        { "id": 142, label: "Chuj", code: "cac" },
        { "id": 143, label: "Ch'ol", code: "ctu" },
        { "id": 144, label: "Tzeltal", code: "tzh" },
        { "id": 145, label: "Chichimeca-Jonaz", code: "pei" },
        { "id": 146, label: "Purépecha", code: "pua" },
        { "id": 147, label: "Yaqui", code: "yaq" },
        { "id": 148, label: "Mayo", code: "yat" },
        { "id": 149, label: "Huichol", code: "hch" },
        { "id": 150, label: "Tepehuán", code: "tpp" },
        { "id": 151, label: "Tarahumara", code: "tar" },
        { "id": 152, label: "Guarijío", code: "var" },
        { "id": 153, label: "Triqui", code: "tru" },
        { "id": 154, label: "Chatino", code: "cot" },
        { "id": 155, label: "Chinantec", code: "ctz" },
        { "id": 156, label: "Mixtec", code: "mto" },
        { "id": 157, label: "Zapoteco", code: "ztg" },
        { "id": 158, label: "Mazateco", code: "vmq" },
        { "id": 159, label: "Popoloca", code: "poo" },
        { "id": 160, label: "Mazahua", code: "maa" },
        { "id": 161, label: "Matlatzinca", code: "ocu" },
        { "id": 162, label: "Totonaco", code: "toc" },
        { "id": 163, label: "Tepehua", code: "tpe" },
        { "id": 164, label: "Pame", code: "pbs" },
        { "id": 165, label: "Chichimeca", code: "cch" },
        { "id": 166, label: "Pima", code: "piw" },
        { "id": 167, label: "Tarasc", code: "tsz" },
        { "id": 168, label: "Trique", code: "trq" },
        { "id": 169, label: "Chatino", code: "cto" },
        { "id": 170, label: "Amuzgo", code: "amu" }
    ],
    ratings: [
        {id: 1, label: "1"},
        {id: 2, label: "2"},
        {id: 3, label: "3"},
        {id: 4, label: "4"},
        {id: 5, label: "5"},
    ], 
   
}


export const commonSlice = createSlice({
    name: "common",
    initialState,
    reducers: {
        updateCommon: (state, action: PayloadAction<Common>) => {
            state.currencies = action.payload.currencies
            state.genders = action.payload.genders
            state.languages = action.payload.languages
            state.ratings = action.payload.ratings
        },
    },


//  extraReducers är en reducer som kan hantera actions från andra slices eller från createAsyncThunk
    // builder är ett objekt som innehåller metoder för att lägga till case reducers
    // med addCase kan vi fånga upp olika action från den asynkrona hämtningen (pending, fulfilled, rejected)
    // https://redux-toolkit.js.org/api/createAsyncThunk
    /* extraReducers: (builder) => {
        builder.addCase(fetchCommon.pending, (state) => {
            state = initialState
        })
        builder.addCase(
            fetchCommon.fulfilled,
            (state, action: PayloadAction<Common>) => {
                state = action.payload
            },
        )
        builder.addCase(fetchCommon.rejected, () => {
            console.error("Error fetching common data")
        })
    }, */
})

// createAsyncThunk tar två argument, ett namn och en funktion som returnerar en promise
/* export const fetchCommon = createAsyncThunk(
    "common/fetchCommon",
    async (urlEndpoint: string) => {
        const response: Response = await fetch(urlEndpoint)
        if (!response.ok) {
            throw new Error("Failed to fetch data from the common object")
        } else {
            const data = await response.json()
            console.log("data.hits in fetchCommon function:", data.hits)
            const fetchedCommon: Common = data.hits 
            return fetchedCommon
        }
    },
) */

// Exporterar alla actionfunktioner
export const { updateCommon } = commonSlice.actions 
// Exporterar reducern
export default commonSlice.reducer

